// src/pages/ToolPage.tsx
import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { Typography, Button, Container } from '@mui/material';

const ToolPage: React.FC = () => {
    const { toolId } = useParams<{ toolId: string }>();

    // Placeholder for tool-specific content
    const renderToolContent = () => {
        switch (toolId) {
            case 'example':
                return <div>Example Tool Content</div>;
            // Add cases for other tools here
            default:
                return <div>Tool not found</div>;
        }
    };

    return (
        <Container>
            <Typography variant="h4" gutterBottom>
                Tool: {toolId}
            </Typography>
            {renderToolContent()}
            <Button variant="contained" component={Link} to="/">
                Back to Tools
            </Button>
        </Container>
    );
};

export default ToolPage;

// src/components/tools/ToolPage.svelte
<script>
  import { onMount } from "svelte";
  import { Link, useParams } from "svelte-routing";
  import ReturnCalc from "./return-calc/ReturnCalc.svelte";
  import RRRCalc from "./rrr-calc/RRRCalc.svelte";
  import { tools } from "../Overview.svelte";

  let toolId;
  let toolName;

  onMount(() => {
    const params = useParams();
    toolId = params.toolId;
    toolName = tools.find((tool) => tool.id.toString() === toolId)?.name || "Unknown Tool";
  });

  const renderToolContent = () => {
    switch (toolId) {
      case "1":
        return ReturnCalc; // Corrected here
      case "2":
        return RRRCalc; // Corrected here
      default:
        return "Tool not found";
    }
  };
</script>

<style>
  .container {
    padding: 16px;
  }
</style>

<div class="container">
  <h1>{toolName}</h1>
  <div>{renderToolContent()}</div>
  <Link to="/" class="back-button">Back to Tools</Link>
</div>
