// src/components/tools/ToolPage.tsx
import React from "react";
import {Link, useParams} from "react-router-dom";
import {Box, Button, Container, Typography} from "@mui/material";
import ReturnCalc from "./return-calc/ReturnCalc";
import {tools} from "../Overview";
import {ArrowBackIosNew} from "@mui/icons-material";
import {RRRCalc} from "./rrr-calc/RRRCalc";

const ToolPage: React.FC = () => {
    const {toolId} = useParams<{ toolId: string }>();

    const renderToolContent = () => {
        switch (toolId) {
            case "1":
                return <ReturnCalc/>;
            case "2":
                return <RRRCalc/>;
            default:
                return <div>Tool not found</div>;
        }
    };

    return (
        <Container sx={{p: 3}}>
            <Typography variant="h4" gutterBottom>
                {tools.find((tool) => tool.id.toString() === toolId)?.name ??
                    "Unknown Tool"}
            </Typography>
            <Box my={3}>{renderToolContent()}</Box>
            <Button
                variant="contained"
                component={Link}
                to="/"
                startIcon={<ArrowBackIosNew/>}
                sx={{mt: 2}}
            >
                Back to Tools
            </Button>
        </Container>
    );
};

export default ToolPage;

// src/components/tools/ToolPage.svelte
<script>
  import { onMount } from "svelte";
  import { Link, useParams } from "svelte-routing";
  import ReturnCalc from "./return-calc/ReturnCalc.svelte";
  import RRRCalc from "./rrr-calc/RRRCalc.svelte";
  import { tools } from "../Overview.svelte";

  let toolId;
  let toolName;

  onMount(() => {
    const params = useParams();
    toolId = params.toolId;
    toolName = tools.find((tool) => tool.id.toString() === toolId)?.name || "Unknown Tool";
  });

  const renderToolContent = () => {
    switch (toolId) {
      case "1":
        return ReturnCalc; // Corrected here
      case "2":
        return RRRCalc; // Corrected here
      default:
        return "Tool not found";
    }
  };
</script>

<style>
  .container {
    padding: 16px;
  }
</style>

<div class="container">
  <h1>{toolName}</h1>
  <div>{renderToolContent()}</div>
  <Link to="/" class="back-button">Back to Tools</Link>
</div>
