// src/components/Overview.svelte
<script>
  import { onMount } from "svelte";
  import { navigate } from "svelte-routing";
  import Tile from "./Tile.svelte";

  export let tools = [
    { id: 1, name: "Return Calculator" },
    { id: 2, name: "RRR Calculator" },
    { id: 3, name: "Tool 3" },
  ];
</script>

<style>
  .container {
    padding: 16px;
  }
  .title {
    font-size: 2rem;
    margin-bottom: 16px;
  }
</style>

<div class="container">
  <h1 class="title">Trading Tools</h1>
  <div class="grid">
    {#each tools as tool}
      <div class="grid-item" on:click={() => navigate(`/tool/${tool.id}`)}>
        <Tile {tool} />
      </div>
    {/each}
  </div>
</div>

// src/components/Overview.tsx
import React from "react";
import {useNavigate} from "react-router-dom";
import {Box, Grid, Typography} from "@mui/material";
import {Tile} from "./Tile";

export type Tool = {
    id: number;
    name: string;
};

export const tools: Tool[] = [
    {id: 1, name: "Return Calculator"},
    {id: 2, name: "RRR Calculator"},
    {id: 3, name: "Tool 3"},
];

const Overview: React.FC = () => {
    const navigate = useNavigate();

    return (
        <Box sx={{p: 3}}>
            <Typography variant="h4" gutterBottom>
                Trading Tools
            </Typography>
            <Grid container spacing={3} justifyContent="flex-start" marginY={3}>
                {tools.map((tool) => (
                    <Grid key={tool.id} size={{xs: 6, md: 2}}>
                        <Tile tool={tool} onClick={() => navigate(`/tool/${tool.id}`)}/>
                    </Grid>
                ))}
            </Grid>
        </Box>
    );
};

export default Overview;
