// src/components/Tile.svelte
<script>
  export let tool;
  export let onClick;
</script>

<style>
  .tile {
    aspect-ratio: 1/1;
    padding: 16px;
    text-align: center;
    border-radius: 8px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: var(--secondary-main);
    color: var(--text-primary);
  }
  .tile:hover {
    background-color: #444;
  }
</style>

<div class="tile" on:click={onClick}>
  <h2>{tool.name}</h2>
</div>

// src/components/Tile.tsx
import { Paper, Typography } from "@mui/material";
import { Tool } from "./Overview";

export const Tile: React.FC<{
  tool: Tool;
  onClick: () => void;
}> = ({ tool, onClick }) => (
  <Paper
    elevation={4}
    sx={{
      aspectRatio: "1/1",
      p: 4,
      textAlign: "center",
      borderRadius: 3,
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      bgcolor: "secondary.main",
      color: "text.primary",
      "&:hover": { bgcolor: "#444" },
    }}
    onClick={onClick}
  >
    <Typography variant="h6">{tool.name}</Typography>
  </Paper>
);
